<?xml version="1.0"?>
<!-- Ghost Compass Biped -->
<robot name="gcb" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="leg_height" value="0.86" /> <!-- Height of leg link -->
  <xacro:property name="talus_height" value="0.1" /> <!-- Height of talus link -->
  <xacro:property name="foot_height" value="0.04" /> <!-- Height of foot link -->
  <xacro:property name="leg_width" value="0.2" /> <!-- Width of each leg link -->
  <xacro:property name="leg_girth" value="0.07" /> <!-- Girth of each leg link -->
  <xacro:property name="foot_length" value="0.2" /> <!-- Length of foot link -->
  <xacro:property name="foot_talus_disp" value="0.045" /> <!-- X displacement between talus and foot -->
  <xacro:property name="leg_mass" value="2.4" /> <!-- Leg link mass -->
  <xacro:property name="talus_mass" value="0.2" /> <!-- Talus link mass -->
  <xacro:property name="foot_mass" value="0.4" /> <!-- Foot link mass -->

  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find gcb_description)/urdf/gcb.gazebo" />
  <!-- Import Rviz colors -->
  <xacro:include filename="$(find gcb_description)/urdf/materials.xacro" />

  <!-- Used for fixing robot to Gazebo 'base_link' -->
  <!-- <link name="world"/>

  <joint name="fixed" type="fixed">
    <parent link="world"/>
    <child link="link1"/>
  </joint> -->

  <!-- Left leg -->
  <link name='pelvis'>
    <collision name='collision'>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.05 0.05 0.05" />
      </geometry>
    </collision>
    
    <visual name='visual'>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.05 0.05 0.05" />
      </geometry>
    </visual>
    
    <inertial name='inertial'>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.01" />
      <inertia ixx="0.000004" ixy="0" ixz="0"
      		iyy="0.000004" iyz="0"
      		izz="0.000004" />
    </inertial>
  </link>
  
  <link name='left_leg'>
    <collision name='collision'>
      <origin xyz="0 0 ${-leg_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${leg_girth} ${leg_width} ${leg_height}" />
      </geometry>
    </collision>
    
    <visual name='visual'>
      <origin xyz="0 0 ${-leg_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${leg_girth} ${leg_width} ${leg_height}" />
      </geometry>
    </visual>
    
    <inertial name='inertial'>
      <origin xyz="0 0 ${-leg_height/2}" rpy="0 0 0"/>
      <mass value="${leg_mass}" />
      <inertia ixx="${1/12*leg_mass*(leg_height*leg_height+leg_width*leg_width)}" ixy="0" ixz="0"
      		iyy="${1/12*leg_mass*(leg_height*leg_height+leg_girth*leg_girth)}" iyz="0"
      		izz="${1/12*leg_mass*(leg_girth*leg_girth+leg_width*leg_width)}" />
    </inertial>
  </link>
  
  
  <link name='left_talus'>
    <collision name='collision'>
      <origin xyz="0 0 ${-talus_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${leg_girth} ${leg_width} ${talus_height}" />
      </geometry>
    </collision>
    
    <visual name='visual'>
      <origin xyz="0 0 ${-talus_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${leg_girth} ${leg_width} ${talus_height}" />
      </geometry>
    </visual>
    
    <inertial name='inertial'>
      <origin xyz="0 0 ${-talus_height/2}" rpy="0 0 0"/>
      <mass value="${talus_mass}" />
      <inertia ixx="${1/12*talus_mass*(talus_height*talus_height+leg_width*leg_width)}" ixy="0" ixz="0"
      		iyy="${1/12*talus_mass*(talus_height*talus_height+leg_girth*leg_girth)}" iyz="0"
      		izz="${1/12*talus_mass*(leg_girth*leg_girth+leg_width*leg_width)}" />
    </inertial>
  </link>
  
  
  <link name='left_foot'>
    <collision name='collision'>
      <origin xyz="0 0 ${-foot_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${foot_length} ${leg_width} ${foot_height}" />
      </geometry>
    </collision>
    
    <visual name='visual'>
      <origin xyz="0 0 ${-foot_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${foot_length} ${leg_width} ${foot_height}" />
      </geometry>
    </visual>
    
    <inertial name='inertial'>
      <origin xyz="0 0 ${-foot_height/2}" rpy="0 0 0"/>
      <mass value="${foot_mass}" />
      <inertia ixx="${1/12*foot_mass*(foot_height*foot_height+leg_width*leg_width)}" ixy="0" ixz="0"
      		iyy="${1/12*foot_mass*(foot_height*foot_height+foot_length*foot_length)}" iyz="0"
      		izz="${1/12*foot_mass*(foot_length*foot_length+leg_width*leg_width)}" />
    </inertial>
  </link>
  
  
  <!-- Right leg -->
  <link name='right_leg'>
    <collision name='collision'>
      <origin xyz="0 0 ${-leg_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${leg_girth} ${leg_width} ${leg_height}" />
      </geometry>
    </collision>
    
    <visual name='visual'>
      <origin xyz="0 0 ${-leg_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${leg_girth} ${leg_width} ${leg_height}" />
      </geometry>
    </visual>
    
    <inertial name='inertial'>
      <origin xyz="0 0 ${-leg_height/2}" rpy="0 0 0"/>
      <mass value="${leg_mass}" />
      <inertia ixx="${1/12*leg_mass*(leg_height*leg_height+leg_width*leg_width)}" ixy="0" ixz="0"
      		iyy="${1/12*leg_mass*(leg_height*leg_height+leg_girth*leg_girth)}" iyz="0"
      		izz="${1/12*leg_mass*(leg_girth*leg_girth+leg_width*leg_width)}" />
    </inertial>
  </link>
  
  
  <link name='right_talus'>
    <collision name='collision'>
      <origin xyz="0 0 ${-talus_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${leg_girth} ${leg_width} ${talus_height}" />
      </geometry>
    </collision>
    
    <visual name='visual'>
      <origin xyz="0 0 ${-talus_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${leg_girth} ${leg_width} ${talus_height}" />
      </geometry>
    </visual>
    
    <inertial name='inertial'>
      <origin xyz="0 0 ${-talus_height/2}" rpy="0 0 0"/>
      <mass value="${talus_mass}" />
      <inertia ixx="${1/12*talus_mass*(talus_height*talus_height+leg_width*leg_width)}" ixy="0" ixz="0"
      		iyy="${1/12*talus_mass*(talus_height*talus_height+leg_girth*leg_girth)}" iyz="0"
      		izz="${1/12*talus_mass*(leg_girth*leg_girth+leg_width*leg_width)}" />
    </inertial>
  </link>
  
  
  <link name='right_foot'>
    <collision name='collision'>
      <origin xyz="0 0 ${-foot_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${foot_length} ${leg_width} ${foot_height}" />
      </geometry>

    </collision>
    <sensor name="bumper_front" type="contact">
        <always_on>true</always_on>
        <update_rate>10</update_rate>
        <visualize>true</visualize>
        <pose>0 0 0   0 0 0</pose>
        <topic>bumper_base</topic>
        <contact>
            <collision>right_foot_collision></collision>
            <topic>bumper_base</topic>
        </contact>

        <plugin name="gazebo_ros_bumper" filename="libgazebo_ros_bumper.so">
            <bumperTopicName>bumper_base</bumperTopicName> 
            <frameName>bumper_base</frameName>
        </plugin> 
    </sensor>
    <visual name='visual'>
      <origin xyz="0 0 ${-foot_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${foot_length} ${leg_width} ${foot_height}" />
      </geometry>
    </visual>
    
    <inertial name='inertial'>
      <origin xyz="0 0 ${-foot_height/2}" rpy="0 0 0"/>
      <mass value="${foot_mass}" />
      <inertia ixx="${1/12*foot_mass*(foot_height*foot_height+leg_width*leg_width)}" ixy="0" ixz="0"
      		iyy="${1/12*foot_mass*(foot_height*foot_height+foot_length*foot_length)}" iyz="0"
      		izz="${1/12*foot_mass*(foot_length*foot_length+leg_width*leg_width)}" />
    </inertial>
  </link>
  <!-- Joints -->
  <joint name="pelvis_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <parent link="left_leg"/>
    <child link="pelvis"/>
  </joint>
  
  <joint name="hip" type="revolute">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <parent link="left_leg"/>
    <child link="right_leg"/>
    <dynamics damping="0.1" friction="0.0"/>
    <limit effort="220" lower="-1.57" upper="1.57" velocity="12"/>
    <safety_controller k_position="100" k_velocity="10" soft_lower_limit="-1.47" soft_upper_limit="1.47"/>
  </joint>
  
  <joint name="left_ankle" type="revolute">
    <origin xyz="0 0 ${-leg_height}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <parent link="left_leg"/>
    <child link="left_talus"/>
    <dynamics damping="0.1" friction="0.0"/>
    <limit effort="220" lower="-1.65" upper="1.3" velocity="12"/>
    <safety_controller k_position="100" k_velocity="10" soft_lower_limit="-1.55" soft_upper_limit="1.2"/>
  </joint>
  
  <joint name="left_foot_ligament" type="fixed">
    <origin xyz="${foot_talus_disp} 0 ${-talus_height}" rpy="0 0 0"/>
    <parent link="left_talus"/>
    <child link="left_foot"/>
  </joint>
  
  <joint name="right_ankle" type="revolute">
    <origin xyz="0 0 ${-leg_height}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <parent link="right_leg"/>
    <child link="right_talus"/>
    <dynamics damping="0.1" friction="0.0"/>
    <limit effort="220" lower="-1.65" upper="1.3" velocity="12"/>
    <safety_controller k_position="100" k_velocity="10" soft_lower_limit="-1.55" soft_upper_limit="1.2"/>
  </joint>
  
  <joint name="right_foot_ligament" type="fixed">
    <origin xyz="${foot_talus_disp} 0 ${-talus_height}" rpy="0 0 0"/>
    <parent link="right_talus"/>
    <child link="right_foot"/>
  </joint>
  

  <transmission name="hip_tran">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="hip"/>
    <actuator name="hip_motor">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  
  <transmission name="lankle_tran">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="left_ankle"/>
    <actuator name="lankle_motor">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="rankle_tran">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="right_ankle"/>
    <actuator name="rankle_motor">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

<!-- <body:empty name="left_foot_force_model_name">
  <sensor:contact name="$left_foot_contact_sensor">
        <geom>$left_foot_geom</geom>
        <updateRate>100.0</updateRate>
        <controller:gazebo_ros_bumper name="$left_foot_gazebo_ros_bumper_controller" plugin="libgazebo_ros_bumper.so">
          <alwaysOn>true</alwaysOn>
          <updateRate>100.0</updateRate>
          <bumperTopicName>$left_foot_bumper</bumperTopicName>
          <interface:bumper name="$left_foot_bumper_iface" />
        </controller:gazebo_ros_bumper>
  </sensor:contact> 
</body:empty> -->

</robot>
